services:
  - type: web
    name: laravel-app
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mainline.proxy.rlwy.net
      - key: DB_PORT
        value: 36455
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ZVMlLVGctllZodYKscOhjxubKlUMlaER
